export type AuditAction =
  | "LOGIN"
  | "PASSWORD_CHANGED"
  | "CALENDAR_CONNECTED"
  | "EVENT_CREATED"
  | "EVENT_UPDATED"
  | "EVENT_DELETED"
  | "REQUEST_ACCEPTED"
  | "REQUEST_REJECTED"
  | "PERMISSION_CHANGED"
  | "ACCOUNT_DELETED";
